/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as BuildIdeaIndexRouteImport } from './../routes/build-idea/index'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as ProjectsViHomeOneRouteRouteImport } from './../routes/projects/vi-home-one/route'
import { Route as ProjectsMolAsmCockpitRouteRouteImport } from './../routes/projects/mol-asm-cockpit/route'
import { Route as ProjectsBshHomeConnectRouteRouteImport } from './../routes/projects/bsh-home-connect/route'
import { Route as ProjectsAdtechIntelligenceRouteRouteImport } from './../routes/projects/adtech-intelligence/route'
import { Route as ProjectsViHomeOneIndexRouteImport } from './../routes/projects/vi-home-one/index'
import { Route as ProjectsMolAsmCockpitIndexRouteImport } from './../routes/projects/mol-asm-cockpit/index'
import { Route as ProjectsBshHomeConnectIndexRouteImport } from './../routes/projects/bsh-home-connect/index'
import { Route as ProjectsAdtechIntelligenceIndexRouteImport } from './../routes/projects/adtech-intelligence/index'
import { Route as ProjectsViHomeOneProfileRouteImport } from './../routes/projects/vi-home-one/profile'
import { Route as ProjectsMolAsmCockpitHomeRouteImport } from './../routes/projects/mol-asm-cockpit/home'
import { Route as ProjectsMolAsmCockpitExplorerRouteImport } from './../routes/projects/mol-asm-cockpit/explorer'
import { Route as ProjectsMolAsmCockpitAgentRouteImport } from './../routes/projects/mol-asm-cockpit/agent'
import { Route as ProjectsBshHomeConnectSupportRouteImport } from './../routes/projects/bsh-home-connect/support'
import { Route as ProjectsBshHomeConnectProfileRouteImport } from './../routes/projects/bsh-home-connect/profile'
import { Route as ProjectsBshHomeConnectDashboardRouteImport } from './../routes/projects/bsh-home-connect/dashboard'
import { Route as ProjectsAdtechIntelligenceProfileRouteImport } from './../routes/projects/adtech-intelligence/profile'
import { Route as ProjectsAdtechIntelligenceIssuesRouteImport } from './../routes/projects/adtech-intelligence/issues'
import { Route as ProjectsAdtechIntelligenceDashboardRouteImport } from './../routes/projects/adtech-intelligence/dashboard'
import { Route as ProjectsViHomeOneSupportIndexRouteImport } from './../routes/projects/vi-home-one/support/index'
import { Route as ProjectsViHomeOneNeighborhoodIndexRouteImport } from './../routes/projects/vi-home-one/neighborhood/index'
import { Route as ProjectsViHomeOneHouseholdsIndexRouteImport } from './../routes/projects/vi-home-one/households/index'
import { Route as ProjectsMolAsmCockpitStationsIndexRouteImport } from './../routes/projects/mol-asm-cockpit/stations/index'
import { Route as ProjectsMolAsmCockpitAnomaliesIndexRouteImport } from './../routes/projects/mol-asm-cockpit/anomalies/index'
import { Route as ProjectsBshHomeConnectTicketsIndexRouteImport } from './../routes/projects/bsh-home-connect/tickets/index'
import { Route as ProjectsBshHomeConnectDevicesIndexRouteImport } from './../routes/projects/bsh-home-connect/devices/index'
import { Route as ProjectsAdtechIntelligenceAnomaliesIndexRouteImport } from './../routes/projects/adtech-intelligence/anomalies/index'
import { Route as ProjectsViHomeOneSupportNewRouteImport } from './../routes/projects/vi-home-one/support/new'
import { Route as ProjectsViHomeOneSupportTicketIdRouteImport } from './../routes/projects/vi-home-one/support/$ticketId'
import { Route as ProjectsViHomeOneHouseholdsHouseholdIdRouteImport } from './../routes/projects/vi-home-one/households/$householdId'
import { Route as ProjectsMolAsmCockpitStationsStationCodeRouteImport } from './../routes/projects/mol-asm-cockpit/stations/$stationCode'
import { Route as ProjectsBshHomeConnectTicketsTicketIdRouteImport } from './../routes/projects/bsh-home-connect/tickets/$ticketId'
import { Route as ProjectsBshHomeConnectDevicesRegisterRouteImport } from './../routes/projects/bsh-home-connect/devices/register'
import { Route as ProjectsAdtechIntelligenceAnomaliesAnomalyIdRouteImport } from './../routes/projects/adtech-intelligence/anomalies/$anomalyId'
import { Route as ProjectsViHomeOneHouseholdsHouseholdIdHistoryRouteImport } from './../routes/projects/vi-home-one/households/$householdId.history'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIdeaIndexRoute = BuildIdeaIndexRouteImport.update({
  id: '/build-idea/',
  path: '/build-idea/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const ProjectsViHomeOneRouteRoute = ProjectsViHomeOneRouteRouteImport.update({
  id: '/projects/vi-home-one',
  path: '/projects/vi-home-one',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMolAsmCockpitRouteRoute =
  ProjectsMolAsmCockpitRouteRouteImport.update({
    id: '/projects/mol-asm-cockpit',
    path: '/projects/mol-asm-cockpit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsBshHomeConnectRouteRoute =
  ProjectsBshHomeConnectRouteRouteImport.update({
    id: '/projects/bsh-home-connect',
    path: '/projects/bsh-home-connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsAdtechIntelligenceRouteRoute =
  ProjectsAdtechIntelligenceRouteRouteImport.update({
    id: '/projects/adtech-intelligence',
    path: '/projects/adtech-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsViHomeOneIndexRoute = ProjectsViHomeOneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsViHomeOneRouteRoute,
} as any)
const ProjectsMolAsmCockpitIndexRoute =
  ProjectsMolAsmCockpitIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsMolAsmCockpitRouteRoute,
  } as any)
const ProjectsBshHomeConnectIndexRoute =
  ProjectsBshHomeConnectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsAdtechIntelligenceIndexRoute =
  ProjectsAdtechIntelligenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsAdtechIntelligenceRouteRoute,
  } as any)
const ProjectsViHomeOneProfileRoute =
  ProjectsViHomeOneProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsMolAsmCockpitHomeRoute =
  ProjectsMolAsmCockpitHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => ProjectsMolAsmCockpitRouteRoute,
  } as any)
const ProjectsMolAsmCockpitExplorerRoute =
  ProjectsMolAsmCockpitExplorerRouteImport.update({
    id: '/explorer',
    path: '/explorer',
    getParentRoute: () => ProjectsMolAsmCockpitRouteRoute,
  } as any)
const ProjectsMolAsmCockpitAgentRoute =
  ProjectsMolAsmCockpitAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => ProjectsMolAsmCockpitRouteRoute,
  } as any)
const ProjectsBshHomeConnectSupportRoute =
  ProjectsBshHomeConnectSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsBshHomeConnectProfileRoute =
  ProjectsBshHomeConnectProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsBshHomeConnectDashboardRoute =
  ProjectsBshHomeConnectDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsAdtechIntelligenceProfileRoute =
  ProjectsAdtechIntelligenceProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProjectsAdtechIntelligenceRouteRoute,
  } as any)
const ProjectsAdtechIntelligenceIssuesRoute =
  ProjectsAdtechIntelligenceIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => ProjectsAdtechIntelligenceRouteRoute,
  } as any)
const ProjectsAdtechIntelligenceDashboardRoute =
  ProjectsAdtechIntelligenceDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProjectsAdtechIntelligenceRouteRoute,
  } as any)
const ProjectsViHomeOneSupportIndexRoute =
  ProjectsViHomeOneSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsViHomeOneNeighborhoodIndexRoute =
  ProjectsViHomeOneNeighborhoodIndexRouteImport.update({
    id: '/neighborhood/',
    path: '/neighborhood/',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsViHomeOneHouseholdsIndexRoute =
  ProjectsViHomeOneHouseholdsIndexRouteImport.update({
    id: '/households/',
    path: '/households/',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsMolAsmCockpitStationsIndexRoute =
  ProjectsMolAsmCockpitStationsIndexRouteImport.update({
    id: '/stations/',
    path: '/stations/',
    getParentRoute: () => ProjectsMolAsmCockpitRouteRoute,
  } as any)
const ProjectsMolAsmCockpitAnomaliesIndexRoute =
  ProjectsMolAsmCockpitAnomaliesIndexRouteImport.update({
    id: '/anomalies/',
    path: '/anomalies/',
    getParentRoute: () => ProjectsMolAsmCockpitRouteRoute,
  } as any)
const ProjectsBshHomeConnectTicketsIndexRoute =
  ProjectsBshHomeConnectTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsBshHomeConnectDevicesIndexRoute =
  ProjectsBshHomeConnectDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsAdtechIntelligenceAnomaliesIndexRoute =
  ProjectsAdtechIntelligenceAnomaliesIndexRouteImport.update({
    id: '/anomalies/',
    path: '/anomalies/',
    getParentRoute: () => ProjectsAdtechIntelligenceRouteRoute,
  } as any)
const ProjectsViHomeOneSupportNewRoute =
  ProjectsViHomeOneSupportNewRouteImport.update({
    id: '/support/new',
    path: '/support/new',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsViHomeOneSupportTicketIdRoute =
  ProjectsViHomeOneSupportTicketIdRouteImport.update({
    id: '/support/$ticketId',
    path: '/support/$ticketId',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsViHomeOneHouseholdsHouseholdIdRoute =
  ProjectsViHomeOneHouseholdsHouseholdIdRouteImport.update({
    id: '/households/$householdId',
    path: '/households/$householdId',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsMolAsmCockpitStationsStationCodeRoute =
  ProjectsMolAsmCockpitStationsStationCodeRouteImport.update({
    id: '/stations/$stationCode',
    path: '/stations/$stationCode',
    getParentRoute: () => ProjectsMolAsmCockpitRouteRoute,
  } as any)
const ProjectsBshHomeConnectTicketsTicketIdRoute =
  ProjectsBshHomeConnectTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsBshHomeConnectDevicesRegisterRoute =
  ProjectsBshHomeConnectDevicesRegisterRouteImport.update({
    id: '/devices/register',
    path: '/devices/register',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsAdtechIntelligenceAnomaliesAnomalyIdRoute =
  ProjectsAdtechIntelligenceAnomaliesAnomalyIdRouteImport.update({
    id: '/anomalies/$anomalyId',
    path: '/anomalies/$anomalyId',
    getParentRoute: () => ProjectsAdtechIntelligenceRouteRoute,
  } as any)
const ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute =
  ProjectsViHomeOneHouseholdsHouseholdIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProjectsViHomeOneHouseholdsHouseholdIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/adtech-intelligence': typeof ProjectsAdtechIntelligenceRouteRouteWithChildren
  '/projects/bsh-home-connect': typeof ProjectsBshHomeConnectRouteRouteWithChildren
  '/projects/mol-asm-cockpit': typeof ProjectsMolAsmCockpitRouteRouteWithChildren
  '/projects/vi-home-one': typeof ProjectsViHomeOneRouteRouteWithChildren
  '/profile': typeof SidebarProfileRoute
  '/build-idea/': typeof BuildIdeaIndexRoute
  '/projects/adtech-intelligence/dashboard': typeof ProjectsAdtechIntelligenceDashboardRoute
  '/projects/adtech-intelligence/issues': typeof ProjectsAdtechIntelligenceIssuesRoute
  '/projects/adtech-intelligence/profile': typeof ProjectsAdtechIntelligenceProfileRoute
  '/projects/bsh-home-connect/dashboard': typeof ProjectsBshHomeConnectDashboardRoute
  '/projects/bsh-home-connect/profile': typeof ProjectsBshHomeConnectProfileRoute
  '/projects/bsh-home-connect/support': typeof ProjectsBshHomeConnectSupportRoute
  '/projects/mol-asm-cockpit/agent': typeof ProjectsMolAsmCockpitAgentRoute
  '/projects/mol-asm-cockpit/explorer': typeof ProjectsMolAsmCockpitExplorerRoute
  '/projects/mol-asm-cockpit/home': typeof ProjectsMolAsmCockpitHomeRoute
  '/projects/vi-home-one/profile': typeof ProjectsViHomeOneProfileRoute
  '/projects/adtech-intelligence/': typeof ProjectsAdtechIntelligenceIndexRoute
  '/projects/bsh-home-connect/': typeof ProjectsBshHomeConnectIndexRoute
  '/projects/mol-asm-cockpit/': typeof ProjectsMolAsmCockpitIndexRoute
  '/projects/vi-home-one/': typeof ProjectsViHomeOneIndexRoute
  '/projects/adtech-intelligence/anomalies/$anomalyId': typeof ProjectsAdtechIntelligenceAnomaliesAnomalyIdRoute
  '/projects/bsh-home-connect/devices/register': typeof ProjectsBshHomeConnectDevicesRegisterRoute
  '/projects/bsh-home-connect/tickets/$ticketId': typeof ProjectsBshHomeConnectTicketsTicketIdRoute
  '/projects/mol-asm-cockpit/stations/$stationCode': typeof ProjectsMolAsmCockpitStationsStationCodeRoute
  '/projects/vi-home-one/households/$householdId': typeof ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren
  '/projects/vi-home-one/support/$ticketId': typeof ProjectsViHomeOneSupportTicketIdRoute
  '/projects/vi-home-one/support/new': typeof ProjectsViHomeOneSupportNewRoute
  '/projects/adtech-intelligence/anomalies/': typeof ProjectsAdtechIntelligenceAnomaliesIndexRoute
  '/projects/bsh-home-connect/devices/': typeof ProjectsBshHomeConnectDevicesIndexRoute
  '/projects/bsh-home-connect/tickets/': typeof ProjectsBshHomeConnectTicketsIndexRoute
  '/projects/mol-asm-cockpit/anomalies/': typeof ProjectsMolAsmCockpitAnomaliesIndexRoute
  '/projects/mol-asm-cockpit/stations/': typeof ProjectsMolAsmCockpitStationsIndexRoute
  '/projects/vi-home-one/households/': typeof ProjectsViHomeOneHouseholdsIndexRoute
  '/projects/vi-home-one/neighborhood/': typeof ProjectsViHomeOneNeighborhoodIndexRoute
  '/projects/vi-home-one/support/': typeof ProjectsViHomeOneSupportIndexRoute
  '/projects/vi-home-one/households/$householdId/history': typeof ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof SidebarProfileRoute
  '/build-idea': typeof BuildIdeaIndexRoute
  '/projects/adtech-intelligence/dashboard': typeof ProjectsAdtechIntelligenceDashboardRoute
  '/projects/adtech-intelligence/issues': typeof ProjectsAdtechIntelligenceIssuesRoute
  '/projects/adtech-intelligence/profile': typeof ProjectsAdtechIntelligenceProfileRoute
  '/projects/bsh-home-connect/dashboard': typeof ProjectsBshHomeConnectDashboardRoute
  '/projects/bsh-home-connect/profile': typeof ProjectsBshHomeConnectProfileRoute
  '/projects/bsh-home-connect/support': typeof ProjectsBshHomeConnectSupportRoute
  '/projects/mol-asm-cockpit/agent': typeof ProjectsMolAsmCockpitAgentRoute
  '/projects/mol-asm-cockpit/explorer': typeof ProjectsMolAsmCockpitExplorerRoute
  '/projects/mol-asm-cockpit/home': typeof ProjectsMolAsmCockpitHomeRoute
  '/projects/vi-home-one/profile': typeof ProjectsViHomeOneProfileRoute
  '/projects/adtech-intelligence': typeof ProjectsAdtechIntelligenceIndexRoute
  '/projects/bsh-home-connect': typeof ProjectsBshHomeConnectIndexRoute
  '/projects/mol-asm-cockpit': typeof ProjectsMolAsmCockpitIndexRoute
  '/projects/vi-home-one': typeof ProjectsViHomeOneIndexRoute
  '/projects/adtech-intelligence/anomalies/$anomalyId': typeof ProjectsAdtechIntelligenceAnomaliesAnomalyIdRoute
  '/projects/bsh-home-connect/devices/register': typeof ProjectsBshHomeConnectDevicesRegisterRoute
  '/projects/bsh-home-connect/tickets/$ticketId': typeof ProjectsBshHomeConnectTicketsTicketIdRoute
  '/projects/mol-asm-cockpit/stations/$stationCode': typeof ProjectsMolAsmCockpitStationsStationCodeRoute
  '/projects/vi-home-one/households/$householdId': typeof ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren
  '/projects/vi-home-one/support/$ticketId': typeof ProjectsViHomeOneSupportTicketIdRoute
  '/projects/vi-home-one/support/new': typeof ProjectsViHomeOneSupportNewRoute
  '/projects/adtech-intelligence/anomalies': typeof ProjectsAdtechIntelligenceAnomaliesIndexRoute
  '/projects/bsh-home-connect/devices': typeof ProjectsBshHomeConnectDevicesIndexRoute
  '/projects/bsh-home-connect/tickets': typeof ProjectsBshHomeConnectTicketsIndexRoute
  '/projects/mol-asm-cockpit/anomalies': typeof ProjectsMolAsmCockpitAnomaliesIndexRoute
  '/projects/mol-asm-cockpit/stations': typeof ProjectsMolAsmCockpitStationsIndexRoute
  '/projects/vi-home-one/households': typeof ProjectsViHomeOneHouseholdsIndexRoute
  '/projects/vi-home-one/neighborhood': typeof ProjectsViHomeOneNeighborhoodIndexRoute
  '/projects/vi-home-one/support': typeof ProjectsViHomeOneSupportIndexRoute
  '/projects/vi-home-one/households/$householdId/history': typeof ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/projects/adtech-intelligence': typeof ProjectsAdtechIntelligenceRouteRouteWithChildren
  '/projects/bsh-home-connect': typeof ProjectsBshHomeConnectRouteRouteWithChildren
  '/projects/mol-asm-cockpit': typeof ProjectsMolAsmCockpitRouteRouteWithChildren
  '/projects/vi-home-one': typeof ProjectsViHomeOneRouteRouteWithChildren
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/build-idea/': typeof BuildIdeaIndexRoute
  '/projects/adtech-intelligence/dashboard': typeof ProjectsAdtechIntelligenceDashboardRoute
  '/projects/adtech-intelligence/issues': typeof ProjectsAdtechIntelligenceIssuesRoute
  '/projects/adtech-intelligence/profile': typeof ProjectsAdtechIntelligenceProfileRoute
  '/projects/bsh-home-connect/dashboard': typeof ProjectsBshHomeConnectDashboardRoute
  '/projects/bsh-home-connect/profile': typeof ProjectsBshHomeConnectProfileRoute
  '/projects/bsh-home-connect/support': typeof ProjectsBshHomeConnectSupportRoute
  '/projects/mol-asm-cockpit/agent': typeof ProjectsMolAsmCockpitAgentRoute
  '/projects/mol-asm-cockpit/explorer': typeof ProjectsMolAsmCockpitExplorerRoute
  '/projects/mol-asm-cockpit/home': typeof ProjectsMolAsmCockpitHomeRoute
  '/projects/vi-home-one/profile': typeof ProjectsViHomeOneProfileRoute
  '/projects/adtech-intelligence/': typeof ProjectsAdtechIntelligenceIndexRoute
  '/projects/bsh-home-connect/': typeof ProjectsBshHomeConnectIndexRoute
  '/projects/mol-asm-cockpit/': typeof ProjectsMolAsmCockpitIndexRoute
  '/projects/vi-home-one/': typeof ProjectsViHomeOneIndexRoute
  '/projects/adtech-intelligence/anomalies/$anomalyId': typeof ProjectsAdtechIntelligenceAnomaliesAnomalyIdRoute
  '/projects/bsh-home-connect/devices/register': typeof ProjectsBshHomeConnectDevicesRegisterRoute
  '/projects/bsh-home-connect/tickets/$ticketId': typeof ProjectsBshHomeConnectTicketsTicketIdRoute
  '/projects/mol-asm-cockpit/stations/$stationCode': typeof ProjectsMolAsmCockpitStationsStationCodeRoute
  '/projects/vi-home-one/households/$householdId': typeof ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren
  '/projects/vi-home-one/support/$ticketId': typeof ProjectsViHomeOneSupportTicketIdRoute
  '/projects/vi-home-one/support/new': typeof ProjectsViHomeOneSupportNewRoute
  '/projects/adtech-intelligence/anomalies/': typeof ProjectsAdtechIntelligenceAnomaliesIndexRoute
  '/projects/bsh-home-connect/devices/': typeof ProjectsBshHomeConnectDevicesIndexRoute
  '/projects/bsh-home-connect/tickets/': typeof ProjectsBshHomeConnectTicketsIndexRoute
  '/projects/mol-asm-cockpit/anomalies/': typeof ProjectsMolAsmCockpitAnomaliesIndexRoute
  '/projects/mol-asm-cockpit/stations/': typeof ProjectsMolAsmCockpitStationsIndexRoute
  '/projects/vi-home-one/households/': typeof ProjectsViHomeOneHouseholdsIndexRoute
  '/projects/vi-home-one/neighborhood/': typeof ProjectsViHomeOneNeighborhoodIndexRoute
  '/projects/vi-home-one/support/': typeof ProjectsViHomeOneSupportIndexRoute
  '/projects/vi-home-one/households/$householdId/history': typeof ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/adtech-intelligence'
    | '/projects/bsh-home-connect'
    | '/projects/mol-asm-cockpit'
    | '/projects/vi-home-one'
    | '/profile'
    | '/build-idea/'
    | '/projects/adtech-intelligence/dashboard'
    | '/projects/adtech-intelligence/issues'
    | '/projects/adtech-intelligence/profile'
    | '/projects/bsh-home-connect/dashboard'
    | '/projects/bsh-home-connect/profile'
    | '/projects/bsh-home-connect/support'
    | '/projects/mol-asm-cockpit/agent'
    | '/projects/mol-asm-cockpit/explorer'
    | '/projects/mol-asm-cockpit/home'
    | '/projects/vi-home-one/profile'
    | '/projects/adtech-intelligence/'
    | '/projects/bsh-home-connect/'
    | '/projects/mol-asm-cockpit/'
    | '/projects/vi-home-one/'
    | '/projects/adtech-intelligence/anomalies/$anomalyId'
    | '/projects/bsh-home-connect/devices/register'
    | '/projects/bsh-home-connect/tickets/$ticketId'
    | '/projects/mol-asm-cockpit/stations/$stationCode'
    | '/projects/vi-home-one/households/$householdId'
    | '/projects/vi-home-one/support/$ticketId'
    | '/projects/vi-home-one/support/new'
    | '/projects/adtech-intelligence/anomalies/'
    | '/projects/bsh-home-connect/devices/'
    | '/projects/bsh-home-connect/tickets/'
    | '/projects/mol-asm-cockpit/anomalies/'
    | '/projects/mol-asm-cockpit/stations/'
    | '/projects/vi-home-one/households/'
    | '/projects/vi-home-one/neighborhood/'
    | '/projects/vi-home-one/support/'
    | '/projects/vi-home-one/households/$householdId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/build-idea'
    | '/projects/adtech-intelligence/dashboard'
    | '/projects/adtech-intelligence/issues'
    | '/projects/adtech-intelligence/profile'
    | '/projects/bsh-home-connect/dashboard'
    | '/projects/bsh-home-connect/profile'
    | '/projects/bsh-home-connect/support'
    | '/projects/mol-asm-cockpit/agent'
    | '/projects/mol-asm-cockpit/explorer'
    | '/projects/mol-asm-cockpit/home'
    | '/projects/vi-home-one/profile'
    | '/projects/adtech-intelligence'
    | '/projects/bsh-home-connect'
    | '/projects/mol-asm-cockpit'
    | '/projects/vi-home-one'
    | '/projects/adtech-intelligence/anomalies/$anomalyId'
    | '/projects/bsh-home-connect/devices/register'
    | '/projects/bsh-home-connect/tickets/$ticketId'
    | '/projects/mol-asm-cockpit/stations/$stationCode'
    | '/projects/vi-home-one/households/$householdId'
    | '/projects/vi-home-one/support/$ticketId'
    | '/projects/vi-home-one/support/new'
    | '/projects/adtech-intelligence/anomalies'
    | '/projects/bsh-home-connect/devices'
    | '/projects/bsh-home-connect/tickets'
    | '/projects/mol-asm-cockpit/anomalies'
    | '/projects/mol-asm-cockpit/stations'
    | '/projects/vi-home-one/households'
    | '/projects/vi-home-one/neighborhood'
    | '/projects/vi-home-one/support'
    | '/projects/vi-home-one/households/$householdId/history'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/projects/adtech-intelligence'
    | '/projects/bsh-home-connect'
    | '/projects/mol-asm-cockpit'
    | '/projects/vi-home-one'
    | '/_sidebar/profile'
    | '/build-idea/'
    | '/projects/adtech-intelligence/dashboard'
    | '/projects/adtech-intelligence/issues'
    | '/projects/adtech-intelligence/profile'
    | '/projects/bsh-home-connect/dashboard'
    | '/projects/bsh-home-connect/profile'
    | '/projects/bsh-home-connect/support'
    | '/projects/mol-asm-cockpit/agent'
    | '/projects/mol-asm-cockpit/explorer'
    | '/projects/mol-asm-cockpit/home'
    | '/projects/vi-home-one/profile'
    | '/projects/adtech-intelligence/'
    | '/projects/bsh-home-connect/'
    | '/projects/mol-asm-cockpit/'
    | '/projects/vi-home-one/'
    | '/projects/adtech-intelligence/anomalies/$anomalyId'
    | '/projects/bsh-home-connect/devices/register'
    | '/projects/bsh-home-connect/tickets/$ticketId'
    | '/projects/mol-asm-cockpit/stations/$stationCode'
    | '/projects/vi-home-one/households/$householdId'
    | '/projects/vi-home-one/support/$ticketId'
    | '/projects/vi-home-one/support/new'
    | '/projects/adtech-intelligence/anomalies/'
    | '/projects/bsh-home-connect/devices/'
    | '/projects/bsh-home-connect/tickets/'
    | '/projects/mol-asm-cockpit/anomalies/'
    | '/projects/mol-asm-cockpit/stations/'
    | '/projects/vi-home-one/households/'
    | '/projects/vi-home-one/neighborhood/'
    | '/projects/vi-home-one/support/'
    | '/projects/vi-home-one/households/$householdId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
  ProjectsAdtechIntelligenceRouteRoute: typeof ProjectsAdtechIntelligenceRouteRouteWithChildren
  ProjectsBshHomeConnectRouteRoute: typeof ProjectsBshHomeConnectRouteRouteWithChildren
  ProjectsMolAsmCockpitRouteRoute: typeof ProjectsMolAsmCockpitRouteRouteWithChildren
  ProjectsViHomeOneRouteRoute: typeof ProjectsViHomeOneRouteRouteWithChildren
  BuildIdeaIndexRoute: typeof BuildIdeaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-idea/': {
      id: '/build-idea/'
      path: '/build-idea'
      fullPath: '/build-idea/'
      preLoaderRoute: typeof BuildIdeaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/projects/vi-home-one': {
      id: '/projects/vi-home-one'
      path: '/projects/vi-home-one'
      fullPath: '/projects/vi-home-one'
      preLoaderRoute: typeof ProjectsViHomeOneRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/mol-asm-cockpit': {
      id: '/projects/mol-asm-cockpit'
      path: '/projects/mol-asm-cockpit'
      fullPath: '/projects/mol-asm-cockpit'
      preLoaderRoute: typeof ProjectsMolAsmCockpitRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/bsh-home-connect': {
      id: '/projects/bsh-home-connect'
      path: '/projects/bsh-home-connect'
      fullPath: '/projects/bsh-home-connect'
      preLoaderRoute: typeof ProjectsBshHomeConnectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/adtech-intelligence': {
      id: '/projects/adtech-intelligence'
      path: '/projects/adtech-intelligence'
      fullPath: '/projects/adtech-intelligence'
      preLoaderRoute: typeof ProjectsAdtechIntelligenceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/vi-home-one/': {
      id: '/projects/vi-home-one/'
      path: '/'
      fullPath: '/projects/vi-home-one/'
      preLoaderRoute: typeof ProjectsViHomeOneIndexRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/mol-asm-cockpit/': {
      id: '/projects/mol-asm-cockpit/'
      path: '/'
      fullPath: '/projects/mol-asm-cockpit/'
      preLoaderRoute: typeof ProjectsMolAsmCockpitIndexRouteImport
      parentRoute: typeof ProjectsMolAsmCockpitRouteRoute
    }
    '/projects/bsh-home-connect/': {
      id: '/projects/bsh-home-connect/'
      path: '/'
      fullPath: '/projects/bsh-home-connect/'
      preLoaderRoute: typeof ProjectsBshHomeConnectIndexRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/adtech-intelligence/': {
      id: '/projects/adtech-intelligence/'
      path: '/'
      fullPath: '/projects/adtech-intelligence/'
      preLoaderRoute: typeof ProjectsAdtechIntelligenceIndexRouteImport
      parentRoute: typeof ProjectsAdtechIntelligenceRouteRoute
    }
    '/projects/vi-home-one/profile': {
      id: '/projects/vi-home-one/profile'
      path: '/profile'
      fullPath: '/projects/vi-home-one/profile'
      preLoaderRoute: typeof ProjectsViHomeOneProfileRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/mol-asm-cockpit/home': {
      id: '/projects/mol-asm-cockpit/home'
      path: '/home'
      fullPath: '/projects/mol-asm-cockpit/home'
      preLoaderRoute: typeof ProjectsMolAsmCockpitHomeRouteImport
      parentRoute: typeof ProjectsMolAsmCockpitRouteRoute
    }
    '/projects/mol-asm-cockpit/explorer': {
      id: '/projects/mol-asm-cockpit/explorer'
      path: '/explorer'
      fullPath: '/projects/mol-asm-cockpit/explorer'
      preLoaderRoute: typeof ProjectsMolAsmCockpitExplorerRouteImport
      parentRoute: typeof ProjectsMolAsmCockpitRouteRoute
    }
    '/projects/mol-asm-cockpit/agent': {
      id: '/projects/mol-asm-cockpit/agent'
      path: '/agent'
      fullPath: '/projects/mol-asm-cockpit/agent'
      preLoaderRoute: typeof ProjectsMolAsmCockpitAgentRouteImport
      parentRoute: typeof ProjectsMolAsmCockpitRouteRoute
    }
    '/projects/bsh-home-connect/support': {
      id: '/projects/bsh-home-connect/support'
      path: '/support'
      fullPath: '/projects/bsh-home-connect/support'
      preLoaderRoute: typeof ProjectsBshHomeConnectSupportRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/bsh-home-connect/profile': {
      id: '/projects/bsh-home-connect/profile'
      path: '/profile'
      fullPath: '/projects/bsh-home-connect/profile'
      preLoaderRoute: typeof ProjectsBshHomeConnectProfileRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/bsh-home-connect/dashboard': {
      id: '/projects/bsh-home-connect/dashboard'
      path: '/dashboard'
      fullPath: '/projects/bsh-home-connect/dashboard'
      preLoaderRoute: typeof ProjectsBshHomeConnectDashboardRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/adtech-intelligence/profile': {
      id: '/projects/adtech-intelligence/profile'
      path: '/profile'
      fullPath: '/projects/adtech-intelligence/profile'
      preLoaderRoute: typeof ProjectsAdtechIntelligenceProfileRouteImport
      parentRoute: typeof ProjectsAdtechIntelligenceRouteRoute
    }
    '/projects/adtech-intelligence/issues': {
      id: '/projects/adtech-intelligence/issues'
      path: '/issues'
      fullPath: '/projects/adtech-intelligence/issues'
      preLoaderRoute: typeof ProjectsAdtechIntelligenceIssuesRouteImport
      parentRoute: typeof ProjectsAdtechIntelligenceRouteRoute
    }
    '/projects/adtech-intelligence/dashboard': {
      id: '/projects/adtech-intelligence/dashboard'
      path: '/dashboard'
      fullPath: '/projects/adtech-intelligence/dashboard'
      preLoaderRoute: typeof ProjectsAdtechIntelligenceDashboardRouteImport
      parentRoute: typeof ProjectsAdtechIntelligenceRouteRoute
    }
    '/projects/vi-home-one/support/': {
      id: '/projects/vi-home-one/support/'
      path: '/support'
      fullPath: '/projects/vi-home-one/support/'
      preLoaderRoute: typeof ProjectsViHomeOneSupportIndexRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/vi-home-one/neighborhood/': {
      id: '/projects/vi-home-one/neighborhood/'
      path: '/neighborhood'
      fullPath: '/projects/vi-home-one/neighborhood/'
      preLoaderRoute: typeof ProjectsViHomeOneNeighborhoodIndexRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/vi-home-one/households/': {
      id: '/projects/vi-home-one/households/'
      path: '/households'
      fullPath: '/projects/vi-home-one/households/'
      preLoaderRoute: typeof ProjectsViHomeOneHouseholdsIndexRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/mol-asm-cockpit/stations/': {
      id: '/projects/mol-asm-cockpit/stations/'
      path: '/stations'
      fullPath: '/projects/mol-asm-cockpit/stations/'
      preLoaderRoute: typeof ProjectsMolAsmCockpitStationsIndexRouteImport
      parentRoute: typeof ProjectsMolAsmCockpitRouteRoute
    }
    '/projects/mol-asm-cockpit/anomalies/': {
      id: '/projects/mol-asm-cockpit/anomalies/'
      path: '/anomalies'
      fullPath: '/projects/mol-asm-cockpit/anomalies/'
      preLoaderRoute: typeof ProjectsMolAsmCockpitAnomaliesIndexRouteImport
      parentRoute: typeof ProjectsMolAsmCockpitRouteRoute
    }
    '/projects/bsh-home-connect/tickets/': {
      id: '/projects/bsh-home-connect/tickets/'
      path: '/tickets'
      fullPath: '/projects/bsh-home-connect/tickets/'
      preLoaderRoute: typeof ProjectsBshHomeConnectTicketsIndexRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/bsh-home-connect/devices/': {
      id: '/projects/bsh-home-connect/devices/'
      path: '/devices'
      fullPath: '/projects/bsh-home-connect/devices/'
      preLoaderRoute: typeof ProjectsBshHomeConnectDevicesIndexRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/adtech-intelligence/anomalies/': {
      id: '/projects/adtech-intelligence/anomalies/'
      path: '/anomalies'
      fullPath: '/projects/adtech-intelligence/anomalies/'
      preLoaderRoute: typeof ProjectsAdtechIntelligenceAnomaliesIndexRouteImport
      parentRoute: typeof ProjectsAdtechIntelligenceRouteRoute
    }
    '/projects/vi-home-one/support/new': {
      id: '/projects/vi-home-one/support/new'
      path: '/support/new'
      fullPath: '/projects/vi-home-one/support/new'
      preLoaderRoute: typeof ProjectsViHomeOneSupportNewRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/vi-home-one/support/$ticketId': {
      id: '/projects/vi-home-one/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/projects/vi-home-one/support/$ticketId'
      preLoaderRoute: typeof ProjectsViHomeOneSupportTicketIdRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/vi-home-one/households/$householdId': {
      id: '/projects/vi-home-one/households/$householdId'
      path: '/households/$householdId'
      fullPath: '/projects/vi-home-one/households/$householdId'
      preLoaderRoute: typeof ProjectsViHomeOneHouseholdsHouseholdIdRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/mol-asm-cockpit/stations/$stationCode': {
      id: '/projects/mol-asm-cockpit/stations/$stationCode'
      path: '/stations/$stationCode'
      fullPath: '/projects/mol-asm-cockpit/stations/$stationCode'
      preLoaderRoute: typeof ProjectsMolAsmCockpitStationsStationCodeRouteImport
      parentRoute: typeof ProjectsMolAsmCockpitRouteRoute
    }
    '/projects/bsh-home-connect/tickets/$ticketId': {
      id: '/projects/bsh-home-connect/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/projects/bsh-home-connect/tickets/$ticketId'
      preLoaderRoute: typeof ProjectsBshHomeConnectTicketsTicketIdRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/bsh-home-connect/devices/register': {
      id: '/projects/bsh-home-connect/devices/register'
      path: '/devices/register'
      fullPath: '/projects/bsh-home-connect/devices/register'
      preLoaderRoute: typeof ProjectsBshHomeConnectDevicesRegisterRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/adtech-intelligence/anomalies/$anomalyId': {
      id: '/projects/adtech-intelligence/anomalies/$anomalyId'
      path: '/anomalies/$anomalyId'
      fullPath: '/projects/adtech-intelligence/anomalies/$anomalyId'
      preLoaderRoute: typeof ProjectsAdtechIntelligenceAnomaliesAnomalyIdRouteImport
      parentRoute: typeof ProjectsAdtechIntelligenceRouteRoute
    }
    '/projects/vi-home-one/households/$householdId/history': {
      id: '/projects/vi-home-one/households/$householdId/history'
      path: '/history'
      fullPath: '/projects/vi-home-one/households/$householdId/history'
      preLoaderRoute: typeof ProjectsViHomeOneHouseholdsHouseholdIdHistoryRouteImport
      parentRoute: typeof ProjectsViHomeOneHouseholdsHouseholdIdRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarProfileRoute: typeof SidebarProfileRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarProfileRoute: SidebarProfileRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

interface ProjectsAdtechIntelligenceRouteRouteChildren {
  ProjectsAdtechIntelligenceDashboardRoute: typeof ProjectsAdtechIntelligenceDashboardRoute
  ProjectsAdtechIntelligenceIssuesRoute: typeof ProjectsAdtechIntelligenceIssuesRoute
  ProjectsAdtechIntelligenceProfileRoute: typeof ProjectsAdtechIntelligenceProfileRoute
  ProjectsAdtechIntelligenceIndexRoute: typeof ProjectsAdtechIntelligenceIndexRoute
  ProjectsAdtechIntelligenceAnomaliesAnomalyIdRoute: typeof ProjectsAdtechIntelligenceAnomaliesAnomalyIdRoute
  ProjectsAdtechIntelligenceAnomaliesIndexRoute: typeof ProjectsAdtechIntelligenceAnomaliesIndexRoute
}

const ProjectsAdtechIntelligenceRouteRouteChildren: ProjectsAdtechIntelligenceRouteRouteChildren =
  {
    ProjectsAdtechIntelligenceDashboardRoute:
      ProjectsAdtechIntelligenceDashboardRoute,
    ProjectsAdtechIntelligenceIssuesRoute:
      ProjectsAdtechIntelligenceIssuesRoute,
    ProjectsAdtechIntelligenceProfileRoute:
      ProjectsAdtechIntelligenceProfileRoute,
    ProjectsAdtechIntelligenceIndexRoute: ProjectsAdtechIntelligenceIndexRoute,
    ProjectsAdtechIntelligenceAnomaliesAnomalyIdRoute:
      ProjectsAdtechIntelligenceAnomaliesAnomalyIdRoute,
    ProjectsAdtechIntelligenceAnomaliesIndexRoute:
      ProjectsAdtechIntelligenceAnomaliesIndexRoute,
  }

const ProjectsAdtechIntelligenceRouteRouteWithChildren =
  ProjectsAdtechIntelligenceRouteRoute._addFileChildren(
    ProjectsAdtechIntelligenceRouteRouteChildren,
  )

interface ProjectsBshHomeConnectRouteRouteChildren {
  ProjectsBshHomeConnectDashboardRoute: typeof ProjectsBshHomeConnectDashboardRoute
  ProjectsBshHomeConnectProfileRoute: typeof ProjectsBshHomeConnectProfileRoute
  ProjectsBshHomeConnectSupportRoute: typeof ProjectsBshHomeConnectSupportRoute
  ProjectsBshHomeConnectIndexRoute: typeof ProjectsBshHomeConnectIndexRoute
  ProjectsBshHomeConnectDevicesRegisterRoute: typeof ProjectsBshHomeConnectDevicesRegisterRoute
  ProjectsBshHomeConnectTicketsTicketIdRoute: typeof ProjectsBshHomeConnectTicketsTicketIdRoute
  ProjectsBshHomeConnectDevicesIndexRoute: typeof ProjectsBshHomeConnectDevicesIndexRoute
  ProjectsBshHomeConnectTicketsIndexRoute: typeof ProjectsBshHomeConnectTicketsIndexRoute
}

const ProjectsBshHomeConnectRouteRouteChildren: ProjectsBshHomeConnectRouteRouteChildren =
  {
    ProjectsBshHomeConnectDashboardRoute: ProjectsBshHomeConnectDashboardRoute,
    ProjectsBshHomeConnectProfileRoute: ProjectsBshHomeConnectProfileRoute,
    ProjectsBshHomeConnectSupportRoute: ProjectsBshHomeConnectSupportRoute,
    ProjectsBshHomeConnectIndexRoute: ProjectsBshHomeConnectIndexRoute,
    ProjectsBshHomeConnectDevicesRegisterRoute:
      ProjectsBshHomeConnectDevicesRegisterRoute,
    ProjectsBshHomeConnectTicketsTicketIdRoute:
      ProjectsBshHomeConnectTicketsTicketIdRoute,
    ProjectsBshHomeConnectDevicesIndexRoute:
      ProjectsBshHomeConnectDevicesIndexRoute,
    ProjectsBshHomeConnectTicketsIndexRoute:
      ProjectsBshHomeConnectTicketsIndexRoute,
  }

const ProjectsBshHomeConnectRouteRouteWithChildren =
  ProjectsBshHomeConnectRouteRoute._addFileChildren(
    ProjectsBshHomeConnectRouteRouteChildren,
  )

interface ProjectsMolAsmCockpitRouteRouteChildren {
  ProjectsMolAsmCockpitAgentRoute: typeof ProjectsMolAsmCockpitAgentRoute
  ProjectsMolAsmCockpitExplorerRoute: typeof ProjectsMolAsmCockpitExplorerRoute
  ProjectsMolAsmCockpitHomeRoute: typeof ProjectsMolAsmCockpitHomeRoute
  ProjectsMolAsmCockpitIndexRoute: typeof ProjectsMolAsmCockpitIndexRoute
  ProjectsMolAsmCockpitStationsStationCodeRoute: typeof ProjectsMolAsmCockpitStationsStationCodeRoute
  ProjectsMolAsmCockpitAnomaliesIndexRoute: typeof ProjectsMolAsmCockpitAnomaliesIndexRoute
  ProjectsMolAsmCockpitStationsIndexRoute: typeof ProjectsMolAsmCockpitStationsIndexRoute
}

const ProjectsMolAsmCockpitRouteRouteChildren: ProjectsMolAsmCockpitRouteRouteChildren =
  {
    ProjectsMolAsmCockpitAgentRoute: ProjectsMolAsmCockpitAgentRoute,
    ProjectsMolAsmCockpitExplorerRoute: ProjectsMolAsmCockpitExplorerRoute,
    ProjectsMolAsmCockpitHomeRoute: ProjectsMolAsmCockpitHomeRoute,
    ProjectsMolAsmCockpitIndexRoute: ProjectsMolAsmCockpitIndexRoute,
    ProjectsMolAsmCockpitStationsStationCodeRoute:
      ProjectsMolAsmCockpitStationsStationCodeRoute,
    ProjectsMolAsmCockpitAnomaliesIndexRoute:
      ProjectsMolAsmCockpitAnomaliesIndexRoute,
    ProjectsMolAsmCockpitStationsIndexRoute:
      ProjectsMolAsmCockpitStationsIndexRoute,
  }

const ProjectsMolAsmCockpitRouteRouteWithChildren =
  ProjectsMolAsmCockpitRouteRoute._addFileChildren(
    ProjectsMolAsmCockpitRouteRouteChildren,
  )

interface ProjectsViHomeOneHouseholdsHouseholdIdRouteChildren {
  ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute: typeof ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute
}

const ProjectsViHomeOneHouseholdsHouseholdIdRouteChildren: ProjectsViHomeOneHouseholdsHouseholdIdRouteChildren =
  {
    ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute:
      ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute,
  }

const ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren =
  ProjectsViHomeOneHouseholdsHouseholdIdRoute._addFileChildren(
    ProjectsViHomeOneHouseholdsHouseholdIdRouteChildren,
  )

interface ProjectsViHomeOneRouteRouteChildren {
  ProjectsViHomeOneProfileRoute: typeof ProjectsViHomeOneProfileRoute
  ProjectsViHomeOneIndexRoute: typeof ProjectsViHomeOneIndexRoute
  ProjectsViHomeOneHouseholdsHouseholdIdRoute: typeof ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren
  ProjectsViHomeOneSupportTicketIdRoute: typeof ProjectsViHomeOneSupportTicketIdRoute
  ProjectsViHomeOneSupportNewRoute: typeof ProjectsViHomeOneSupportNewRoute
  ProjectsViHomeOneHouseholdsIndexRoute: typeof ProjectsViHomeOneHouseholdsIndexRoute
  ProjectsViHomeOneNeighborhoodIndexRoute: typeof ProjectsViHomeOneNeighborhoodIndexRoute
  ProjectsViHomeOneSupportIndexRoute: typeof ProjectsViHomeOneSupportIndexRoute
}

const ProjectsViHomeOneRouteRouteChildren: ProjectsViHomeOneRouteRouteChildren =
  {
    ProjectsViHomeOneProfileRoute: ProjectsViHomeOneProfileRoute,
    ProjectsViHomeOneIndexRoute: ProjectsViHomeOneIndexRoute,
    ProjectsViHomeOneHouseholdsHouseholdIdRoute:
      ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren,
    ProjectsViHomeOneSupportTicketIdRoute:
      ProjectsViHomeOneSupportTicketIdRoute,
    ProjectsViHomeOneSupportNewRoute: ProjectsViHomeOneSupportNewRoute,
    ProjectsViHomeOneHouseholdsIndexRoute:
      ProjectsViHomeOneHouseholdsIndexRoute,
    ProjectsViHomeOneNeighborhoodIndexRoute:
      ProjectsViHomeOneNeighborhoodIndexRoute,
    ProjectsViHomeOneSupportIndexRoute: ProjectsViHomeOneSupportIndexRoute,
  }

const ProjectsViHomeOneRouteRouteWithChildren =
  ProjectsViHomeOneRouteRoute._addFileChildren(
    ProjectsViHomeOneRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
  ProjectsAdtechIntelligenceRouteRoute:
    ProjectsAdtechIntelligenceRouteRouteWithChildren,
  ProjectsBshHomeConnectRouteRoute:
    ProjectsBshHomeConnectRouteRouteWithChildren,
  ProjectsMolAsmCockpitRouteRoute: ProjectsMolAsmCockpitRouteRouteWithChildren,
  ProjectsViHomeOneRouteRoute: ProjectsViHomeOneRouteRouteWithChildren,
  BuildIdeaIndexRoute: BuildIdeaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
