/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as BuildIdeaIndexRouteImport } from './../routes/build-idea/index'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as ProjectsViHomeOneRouteRouteImport } from './../routes/projects/vi-home-one/route'
import { Route as ProjectsBshHomeConnectRouteRouteImport } from './../routes/projects/bsh-home-connect/route'
import { Route as ProjectsViHomeOneIndexRouteImport } from './../routes/projects/vi-home-one/index'
import { Route as ProjectsBshHomeConnectIndexRouteImport } from './../routes/projects/bsh-home-connect/index'
import { Route as ProjectsViHomeOneProfileRouteImport } from './../routes/projects/vi-home-one/profile'
import { Route as ProjectsBshHomeConnectSupportRouteImport } from './../routes/projects/bsh-home-connect/support'
import { Route as ProjectsBshHomeConnectProfileRouteImport } from './../routes/projects/bsh-home-connect/profile'
import { Route as ProjectsBshHomeConnectDashboardRouteImport } from './../routes/projects/bsh-home-connect/dashboard'
import { Route as ProjectsViHomeOneSupportIndexRouteImport } from './../routes/projects/vi-home-one/support/index'
import { Route as ProjectsViHomeOneNeighborhoodIndexRouteImport } from './../routes/projects/vi-home-one/neighborhood/index'
import { Route as ProjectsViHomeOneHouseholdsIndexRouteImport } from './../routes/projects/vi-home-one/households/index'
import { Route as ProjectsBshHomeConnectTicketsIndexRouteImport } from './../routes/projects/bsh-home-connect/tickets/index'
import { Route as ProjectsBshHomeConnectDevicesIndexRouteImport } from './../routes/projects/bsh-home-connect/devices/index'
import { Route as ProjectsViHomeOneSupportNewRouteImport } from './../routes/projects/vi-home-one/support/new'
import { Route as ProjectsViHomeOneSupportTicketIdRouteImport } from './../routes/projects/vi-home-one/support/$ticketId'
import { Route as ProjectsViHomeOneHouseholdsHouseholdIdRouteImport } from './../routes/projects/vi-home-one/households/$householdId'
import { Route as ProjectsBshHomeConnectTicketsTicketIdRouteImport } from './../routes/projects/bsh-home-connect/tickets/$ticketId'
import { Route as ProjectsBshHomeConnectDevicesRegisterRouteImport } from './../routes/projects/bsh-home-connect/devices/register'
import { Route as ProjectsViHomeOneHouseholdsHouseholdIdHistoryRouteImport } from './../routes/projects/vi-home-one/households/$householdId.history'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIdeaIndexRoute = BuildIdeaIndexRouteImport.update({
  id: '/build-idea/',
  path: '/build-idea/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const ProjectsViHomeOneRouteRoute = ProjectsViHomeOneRouteRouteImport.update({
  id: '/projects/vi-home-one',
  path: '/projects/vi-home-one',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBshHomeConnectRouteRoute =
  ProjectsBshHomeConnectRouteRouteImport.update({
    id: '/projects/bsh-home-connect',
    path: '/projects/bsh-home-connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsViHomeOneIndexRoute = ProjectsViHomeOneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsViHomeOneRouteRoute,
} as any)
const ProjectsBshHomeConnectIndexRoute =
  ProjectsBshHomeConnectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsViHomeOneProfileRoute =
  ProjectsViHomeOneProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsBshHomeConnectSupportRoute =
  ProjectsBshHomeConnectSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsBshHomeConnectProfileRoute =
  ProjectsBshHomeConnectProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsBshHomeConnectDashboardRoute =
  ProjectsBshHomeConnectDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsViHomeOneSupportIndexRoute =
  ProjectsViHomeOneSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsViHomeOneNeighborhoodIndexRoute =
  ProjectsViHomeOneNeighborhoodIndexRouteImport.update({
    id: '/neighborhood/',
    path: '/neighborhood/',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsViHomeOneHouseholdsIndexRoute =
  ProjectsViHomeOneHouseholdsIndexRouteImport.update({
    id: '/households/',
    path: '/households/',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsBshHomeConnectTicketsIndexRoute =
  ProjectsBshHomeConnectTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsBshHomeConnectDevicesIndexRoute =
  ProjectsBshHomeConnectDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsViHomeOneSupportNewRoute =
  ProjectsViHomeOneSupportNewRouteImport.update({
    id: '/support/new',
    path: '/support/new',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsViHomeOneSupportTicketIdRoute =
  ProjectsViHomeOneSupportTicketIdRouteImport.update({
    id: '/support/$ticketId',
    path: '/support/$ticketId',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsViHomeOneHouseholdsHouseholdIdRoute =
  ProjectsViHomeOneHouseholdsHouseholdIdRouteImport.update({
    id: '/households/$householdId',
    path: '/households/$householdId',
    getParentRoute: () => ProjectsViHomeOneRouteRoute,
  } as any)
const ProjectsBshHomeConnectTicketsTicketIdRoute =
  ProjectsBshHomeConnectTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsBshHomeConnectDevicesRegisterRoute =
  ProjectsBshHomeConnectDevicesRegisterRouteImport.update({
    id: '/devices/register',
    path: '/devices/register',
    getParentRoute: () => ProjectsBshHomeConnectRouteRoute,
  } as any)
const ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute =
  ProjectsViHomeOneHouseholdsHouseholdIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProjectsViHomeOneHouseholdsHouseholdIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/bsh-home-connect': typeof ProjectsBshHomeConnectRouteRouteWithChildren
  '/projects/vi-home-one': typeof ProjectsViHomeOneRouteRouteWithChildren
  '/profile': typeof SidebarProfileRoute
  '/build-idea/': typeof BuildIdeaIndexRoute
  '/projects/bsh-home-connect/dashboard': typeof ProjectsBshHomeConnectDashboardRoute
  '/projects/bsh-home-connect/profile': typeof ProjectsBshHomeConnectProfileRoute
  '/projects/bsh-home-connect/support': typeof ProjectsBshHomeConnectSupportRoute
  '/projects/vi-home-one/profile': typeof ProjectsViHomeOneProfileRoute
  '/projects/bsh-home-connect/': typeof ProjectsBshHomeConnectIndexRoute
  '/projects/vi-home-one/': typeof ProjectsViHomeOneIndexRoute
  '/projects/bsh-home-connect/devices/register': typeof ProjectsBshHomeConnectDevicesRegisterRoute
  '/projects/bsh-home-connect/tickets/$ticketId': typeof ProjectsBshHomeConnectTicketsTicketIdRoute
  '/projects/vi-home-one/households/$householdId': typeof ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren
  '/projects/vi-home-one/support/$ticketId': typeof ProjectsViHomeOneSupportTicketIdRoute
  '/projects/vi-home-one/support/new': typeof ProjectsViHomeOneSupportNewRoute
  '/projects/bsh-home-connect/devices/': typeof ProjectsBshHomeConnectDevicesIndexRoute
  '/projects/bsh-home-connect/tickets/': typeof ProjectsBshHomeConnectTicketsIndexRoute
  '/projects/vi-home-one/households/': typeof ProjectsViHomeOneHouseholdsIndexRoute
  '/projects/vi-home-one/neighborhood/': typeof ProjectsViHomeOneNeighborhoodIndexRoute
  '/projects/vi-home-one/support/': typeof ProjectsViHomeOneSupportIndexRoute
  '/projects/vi-home-one/households/$householdId/history': typeof ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof SidebarProfileRoute
  '/build-idea': typeof BuildIdeaIndexRoute
  '/projects/bsh-home-connect/dashboard': typeof ProjectsBshHomeConnectDashboardRoute
  '/projects/bsh-home-connect/profile': typeof ProjectsBshHomeConnectProfileRoute
  '/projects/bsh-home-connect/support': typeof ProjectsBshHomeConnectSupportRoute
  '/projects/vi-home-one/profile': typeof ProjectsViHomeOneProfileRoute
  '/projects/bsh-home-connect': typeof ProjectsBshHomeConnectIndexRoute
  '/projects/vi-home-one': typeof ProjectsViHomeOneIndexRoute
  '/projects/bsh-home-connect/devices/register': typeof ProjectsBshHomeConnectDevicesRegisterRoute
  '/projects/bsh-home-connect/tickets/$ticketId': typeof ProjectsBshHomeConnectTicketsTicketIdRoute
  '/projects/vi-home-one/households/$householdId': typeof ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren
  '/projects/vi-home-one/support/$ticketId': typeof ProjectsViHomeOneSupportTicketIdRoute
  '/projects/vi-home-one/support/new': typeof ProjectsViHomeOneSupportNewRoute
  '/projects/bsh-home-connect/devices': typeof ProjectsBshHomeConnectDevicesIndexRoute
  '/projects/bsh-home-connect/tickets': typeof ProjectsBshHomeConnectTicketsIndexRoute
  '/projects/vi-home-one/households': typeof ProjectsViHomeOneHouseholdsIndexRoute
  '/projects/vi-home-one/neighborhood': typeof ProjectsViHomeOneNeighborhoodIndexRoute
  '/projects/vi-home-one/support': typeof ProjectsViHomeOneSupportIndexRoute
  '/projects/vi-home-one/households/$householdId/history': typeof ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/projects/bsh-home-connect': typeof ProjectsBshHomeConnectRouteRouteWithChildren
  '/projects/vi-home-one': typeof ProjectsViHomeOneRouteRouteWithChildren
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/build-idea/': typeof BuildIdeaIndexRoute
  '/projects/bsh-home-connect/dashboard': typeof ProjectsBshHomeConnectDashboardRoute
  '/projects/bsh-home-connect/profile': typeof ProjectsBshHomeConnectProfileRoute
  '/projects/bsh-home-connect/support': typeof ProjectsBshHomeConnectSupportRoute
  '/projects/vi-home-one/profile': typeof ProjectsViHomeOneProfileRoute
  '/projects/bsh-home-connect/': typeof ProjectsBshHomeConnectIndexRoute
  '/projects/vi-home-one/': typeof ProjectsViHomeOneIndexRoute
  '/projects/bsh-home-connect/devices/register': typeof ProjectsBshHomeConnectDevicesRegisterRoute
  '/projects/bsh-home-connect/tickets/$ticketId': typeof ProjectsBshHomeConnectTicketsTicketIdRoute
  '/projects/vi-home-one/households/$householdId': typeof ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren
  '/projects/vi-home-one/support/$ticketId': typeof ProjectsViHomeOneSupportTicketIdRoute
  '/projects/vi-home-one/support/new': typeof ProjectsViHomeOneSupportNewRoute
  '/projects/bsh-home-connect/devices/': typeof ProjectsBshHomeConnectDevicesIndexRoute
  '/projects/bsh-home-connect/tickets/': typeof ProjectsBshHomeConnectTicketsIndexRoute
  '/projects/vi-home-one/households/': typeof ProjectsViHomeOneHouseholdsIndexRoute
  '/projects/vi-home-one/neighborhood/': typeof ProjectsViHomeOneNeighborhoodIndexRoute
  '/projects/vi-home-one/support/': typeof ProjectsViHomeOneSupportIndexRoute
  '/projects/vi-home-one/households/$householdId/history': typeof ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/bsh-home-connect'
    | '/projects/vi-home-one'
    | '/profile'
    | '/build-idea/'
    | '/projects/bsh-home-connect/dashboard'
    | '/projects/bsh-home-connect/profile'
    | '/projects/bsh-home-connect/support'
    | '/projects/vi-home-one/profile'
    | '/projects/bsh-home-connect/'
    | '/projects/vi-home-one/'
    | '/projects/bsh-home-connect/devices/register'
    | '/projects/bsh-home-connect/tickets/$ticketId'
    | '/projects/vi-home-one/households/$householdId'
    | '/projects/vi-home-one/support/$ticketId'
    | '/projects/vi-home-one/support/new'
    | '/projects/bsh-home-connect/devices/'
    | '/projects/bsh-home-connect/tickets/'
    | '/projects/vi-home-one/households/'
    | '/projects/vi-home-one/neighborhood/'
    | '/projects/vi-home-one/support/'
    | '/projects/vi-home-one/households/$householdId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/build-idea'
    | '/projects/bsh-home-connect/dashboard'
    | '/projects/bsh-home-connect/profile'
    | '/projects/bsh-home-connect/support'
    | '/projects/vi-home-one/profile'
    | '/projects/bsh-home-connect'
    | '/projects/vi-home-one'
    | '/projects/bsh-home-connect/devices/register'
    | '/projects/bsh-home-connect/tickets/$ticketId'
    | '/projects/vi-home-one/households/$householdId'
    | '/projects/vi-home-one/support/$ticketId'
    | '/projects/vi-home-one/support/new'
    | '/projects/bsh-home-connect/devices'
    | '/projects/bsh-home-connect/tickets'
    | '/projects/vi-home-one/households'
    | '/projects/vi-home-one/neighborhood'
    | '/projects/vi-home-one/support'
    | '/projects/vi-home-one/households/$householdId/history'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/projects/bsh-home-connect'
    | '/projects/vi-home-one'
    | '/_sidebar/profile'
    | '/build-idea/'
    | '/projects/bsh-home-connect/dashboard'
    | '/projects/bsh-home-connect/profile'
    | '/projects/bsh-home-connect/support'
    | '/projects/vi-home-one/profile'
    | '/projects/bsh-home-connect/'
    | '/projects/vi-home-one/'
    | '/projects/bsh-home-connect/devices/register'
    | '/projects/bsh-home-connect/tickets/$ticketId'
    | '/projects/vi-home-one/households/$householdId'
    | '/projects/vi-home-one/support/$ticketId'
    | '/projects/vi-home-one/support/new'
    | '/projects/bsh-home-connect/devices/'
    | '/projects/bsh-home-connect/tickets/'
    | '/projects/vi-home-one/households/'
    | '/projects/vi-home-one/neighborhood/'
    | '/projects/vi-home-one/support/'
    | '/projects/vi-home-one/households/$householdId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
  ProjectsBshHomeConnectRouteRoute: typeof ProjectsBshHomeConnectRouteRouteWithChildren
  ProjectsViHomeOneRouteRoute: typeof ProjectsViHomeOneRouteRouteWithChildren
  BuildIdeaIndexRoute: typeof BuildIdeaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-idea/': {
      id: '/build-idea/'
      path: '/build-idea'
      fullPath: '/build-idea/'
      preLoaderRoute: typeof BuildIdeaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/projects/vi-home-one': {
      id: '/projects/vi-home-one'
      path: '/projects/vi-home-one'
      fullPath: '/projects/vi-home-one'
      preLoaderRoute: typeof ProjectsViHomeOneRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/bsh-home-connect': {
      id: '/projects/bsh-home-connect'
      path: '/projects/bsh-home-connect'
      fullPath: '/projects/bsh-home-connect'
      preLoaderRoute: typeof ProjectsBshHomeConnectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/vi-home-one/': {
      id: '/projects/vi-home-one/'
      path: '/'
      fullPath: '/projects/vi-home-one/'
      preLoaderRoute: typeof ProjectsViHomeOneIndexRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/bsh-home-connect/': {
      id: '/projects/bsh-home-connect/'
      path: '/'
      fullPath: '/projects/bsh-home-connect/'
      preLoaderRoute: typeof ProjectsBshHomeConnectIndexRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/vi-home-one/profile': {
      id: '/projects/vi-home-one/profile'
      path: '/profile'
      fullPath: '/projects/vi-home-one/profile'
      preLoaderRoute: typeof ProjectsViHomeOneProfileRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/bsh-home-connect/support': {
      id: '/projects/bsh-home-connect/support'
      path: '/support'
      fullPath: '/projects/bsh-home-connect/support'
      preLoaderRoute: typeof ProjectsBshHomeConnectSupportRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/bsh-home-connect/profile': {
      id: '/projects/bsh-home-connect/profile'
      path: '/profile'
      fullPath: '/projects/bsh-home-connect/profile'
      preLoaderRoute: typeof ProjectsBshHomeConnectProfileRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/bsh-home-connect/dashboard': {
      id: '/projects/bsh-home-connect/dashboard'
      path: '/dashboard'
      fullPath: '/projects/bsh-home-connect/dashboard'
      preLoaderRoute: typeof ProjectsBshHomeConnectDashboardRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/vi-home-one/support/': {
      id: '/projects/vi-home-one/support/'
      path: '/support'
      fullPath: '/projects/vi-home-one/support/'
      preLoaderRoute: typeof ProjectsViHomeOneSupportIndexRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/vi-home-one/neighborhood/': {
      id: '/projects/vi-home-one/neighborhood/'
      path: '/neighborhood'
      fullPath: '/projects/vi-home-one/neighborhood/'
      preLoaderRoute: typeof ProjectsViHomeOneNeighborhoodIndexRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/vi-home-one/households/': {
      id: '/projects/vi-home-one/households/'
      path: '/households'
      fullPath: '/projects/vi-home-one/households/'
      preLoaderRoute: typeof ProjectsViHomeOneHouseholdsIndexRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/bsh-home-connect/tickets/': {
      id: '/projects/bsh-home-connect/tickets/'
      path: '/tickets'
      fullPath: '/projects/bsh-home-connect/tickets/'
      preLoaderRoute: typeof ProjectsBshHomeConnectTicketsIndexRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/bsh-home-connect/devices/': {
      id: '/projects/bsh-home-connect/devices/'
      path: '/devices'
      fullPath: '/projects/bsh-home-connect/devices/'
      preLoaderRoute: typeof ProjectsBshHomeConnectDevicesIndexRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/vi-home-one/support/new': {
      id: '/projects/vi-home-one/support/new'
      path: '/support/new'
      fullPath: '/projects/vi-home-one/support/new'
      preLoaderRoute: typeof ProjectsViHomeOneSupportNewRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/vi-home-one/support/$ticketId': {
      id: '/projects/vi-home-one/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/projects/vi-home-one/support/$ticketId'
      preLoaderRoute: typeof ProjectsViHomeOneSupportTicketIdRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/vi-home-one/households/$householdId': {
      id: '/projects/vi-home-one/households/$householdId'
      path: '/households/$householdId'
      fullPath: '/projects/vi-home-one/households/$householdId'
      preLoaderRoute: typeof ProjectsViHomeOneHouseholdsHouseholdIdRouteImport
      parentRoute: typeof ProjectsViHomeOneRouteRoute
    }
    '/projects/bsh-home-connect/tickets/$ticketId': {
      id: '/projects/bsh-home-connect/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/projects/bsh-home-connect/tickets/$ticketId'
      preLoaderRoute: typeof ProjectsBshHomeConnectTicketsTicketIdRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/bsh-home-connect/devices/register': {
      id: '/projects/bsh-home-connect/devices/register'
      path: '/devices/register'
      fullPath: '/projects/bsh-home-connect/devices/register'
      preLoaderRoute: typeof ProjectsBshHomeConnectDevicesRegisterRouteImport
      parentRoute: typeof ProjectsBshHomeConnectRouteRoute
    }
    '/projects/vi-home-one/households/$householdId/history': {
      id: '/projects/vi-home-one/households/$householdId/history'
      path: '/history'
      fullPath: '/projects/vi-home-one/households/$householdId/history'
      preLoaderRoute: typeof ProjectsViHomeOneHouseholdsHouseholdIdHistoryRouteImport
      parentRoute: typeof ProjectsViHomeOneHouseholdsHouseholdIdRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarProfileRoute: typeof SidebarProfileRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarProfileRoute: SidebarProfileRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

interface ProjectsBshHomeConnectRouteRouteChildren {
  ProjectsBshHomeConnectDashboardRoute: typeof ProjectsBshHomeConnectDashboardRoute
  ProjectsBshHomeConnectProfileRoute: typeof ProjectsBshHomeConnectProfileRoute
  ProjectsBshHomeConnectSupportRoute: typeof ProjectsBshHomeConnectSupportRoute
  ProjectsBshHomeConnectIndexRoute: typeof ProjectsBshHomeConnectIndexRoute
  ProjectsBshHomeConnectDevicesRegisterRoute: typeof ProjectsBshHomeConnectDevicesRegisterRoute
  ProjectsBshHomeConnectTicketsTicketIdRoute: typeof ProjectsBshHomeConnectTicketsTicketIdRoute
  ProjectsBshHomeConnectDevicesIndexRoute: typeof ProjectsBshHomeConnectDevicesIndexRoute
  ProjectsBshHomeConnectTicketsIndexRoute: typeof ProjectsBshHomeConnectTicketsIndexRoute
}

const ProjectsBshHomeConnectRouteRouteChildren: ProjectsBshHomeConnectRouteRouteChildren =
  {
    ProjectsBshHomeConnectDashboardRoute: ProjectsBshHomeConnectDashboardRoute,
    ProjectsBshHomeConnectProfileRoute: ProjectsBshHomeConnectProfileRoute,
    ProjectsBshHomeConnectSupportRoute: ProjectsBshHomeConnectSupportRoute,
    ProjectsBshHomeConnectIndexRoute: ProjectsBshHomeConnectIndexRoute,
    ProjectsBshHomeConnectDevicesRegisterRoute:
      ProjectsBshHomeConnectDevicesRegisterRoute,
    ProjectsBshHomeConnectTicketsTicketIdRoute:
      ProjectsBshHomeConnectTicketsTicketIdRoute,
    ProjectsBshHomeConnectDevicesIndexRoute:
      ProjectsBshHomeConnectDevicesIndexRoute,
    ProjectsBshHomeConnectTicketsIndexRoute:
      ProjectsBshHomeConnectTicketsIndexRoute,
  }

const ProjectsBshHomeConnectRouteRouteWithChildren =
  ProjectsBshHomeConnectRouteRoute._addFileChildren(
    ProjectsBshHomeConnectRouteRouteChildren,
  )

interface ProjectsViHomeOneHouseholdsHouseholdIdRouteChildren {
  ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute: typeof ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute
}

const ProjectsViHomeOneHouseholdsHouseholdIdRouteChildren: ProjectsViHomeOneHouseholdsHouseholdIdRouteChildren =
  {
    ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute:
      ProjectsViHomeOneHouseholdsHouseholdIdHistoryRoute,
  }

const ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren =
  ProjectsViHomeOneHouseholdsHouseholdIdRoute._addFileChildren(
    ProjectsViHomeOneHouseholdsHouseholdIdRouteChildren,
  )

interface ProjectsViHomeOneRouteRouteChildren {
  ProjectsViHomeOneProfileRoute: typeof ProjectsViHomeOneProfileRoute
  ProjectsViHomeOneIndexRoute: typeof ProjectsViHomeOneIndexRoute
  ProjectsViHomeOneHouseholdsHouseholdIdRoute: typeof ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren
  ProjectsViHomeOneSupportTicketIdRoute: typeof ProjectsViHomeOneSupportTicketIdRoute
  ProjectsViHomeOneSupportNewRoute: typeof ProjectsViHomeOneSupportNewRoute
  ProjectsViHomeOneHouseholdsIndexRoute: typeof ProjectsViHomeOneHouseholdsIndexRoute
  ProjectsViHomeOneNeighborhoodIndexRoute: typeof ProjectsViHomeOneNeighborhoodIndexRoute
  ProjectsViHomeOneSupportIndexRoute: typeof ProjectsViHomeOneSupportIndexRoute
}

const ProjectsViHomeOneRouteRouteChildren: ProjectsViHomeOneRouteRouteChildren =
  {
    ProjectsViHomeOneProfileRoute: ProjectsViHomeOneProfileRoute,
    ProjectsViHomeOneIndexRoute: ProjectsViHomeOneIndexRoute,
    ProjectsViHomeOneHouseholdsHouseholdIdRoute:
      ProjectsViHomeOneHouseholdsHouseholdIdRouteWithChildren,
    ProjectsViHomeOneSupportTicketIdRoute:
      ProjectsViHomeOneSupportTicketIdRoute,
    ProjectsViHomeOneSupportNewRoute: ProjectsViHomeOneSupportNewRoute,
    ProjectsViHomeOneHouseholdsIndexRoute:
      ProjectsViHomeOneHouseholdsIndexRoute,
    ProjectsViHomeOneNeighborhoodIndexRoute:
      ProjectsViHomeOneNeighborhoodIndexRoute,
    ProjectsViHomeOneSupportIndexRoute: ProjectsViHomeOneSupportIndexRoute,
  }

const ProjectsViHomeOneRouteRouteWithChildren =
  ProjectsViHomeOneRouteRoute._addFileChildren(
    ProjectsViHomeOneRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
  ProjectsBshHomeConnectRouteRoute:
    ProjectsBshHomeConnectRouteRouteWithChildren,
  ProjectsViHomeOneRouteRoute: ProjectsViHomeOneRouteRouteWithChildren,
  BuildIdeaIndexRoute: BuildIdeaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
